server:
  port: 8080
  
spring:
  #springboot上传文件大小限制
  servlet:  
    multipart: 
      enabled: true  #表示可以启动http上传
      max-file-size: 20MB
      max-request-size: 200MB
  datasource:  
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.110.46.60:3306/a_note?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT%2b8
    username: root
    password: A_notemysql1.0
jwt:
  #jwt（第三段数据）加密密钥
  password: pswd_for_A_Note
  #jwt超时时间24h(24*3600*1000ms)
  expiry: 86400000

mybatis-plus: 
  mapper-locations: classpath*:com/hhhao/note/mapper/xml/*Mapper.xml
  type-aliases-package: com.hhhao.note.entity
  check-config-location: false
  executor-type: simple
  configuration:
    map-underscore-to-camel-case: true
    jdbc-type-for-null: null
    #log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    column-underline: true
    banner: false  #是否显示mybatis-plus的图标
    db-config:
      logic-delete-value: 1       # 逻辑已删除值(逻辑删除下有效)
      logic-not-delete-value: 0
      
thymeleaf:
  #缓存设置为false，这样修改之后马上生效，便于调试
  cache: false
   # 前缀
  prefix: classpath:/thymeleaf/
   # 后缀
  suffix: .html
  encoding: UTF-8
  content-type: text/html
  mode: HTML